#! /bin/zsh

# set flag vars to empty 

file=	verbose=     quiet=	long=

while getopts :f:vql opt
do
	case $opt in
	
	f)
		file=$OPTARG
		;;
	v)
		verbose=true
		;;
	q)
		quiet=true
		;;
	l)	
		long=true
		;;
	'?') 
		echo "$0 invalid option -$OPTARG" >&2
		echo "usage: $0 [-f file] [-vlq] [files ...]" >&2
		exit 1
		;;
	esac
done


