#! /bin/bash

for f in file*.xml
do
	echo $f
	mv $f $f.old
	awk -F: '{ print $5 }' /etc/passwd | sed 's/^$/@@@/' > $f
       	
	if test $? -eq 0
	then 
		echo file $f changed 
	else
		echo error 
		exit 1 
	fi	
done

echo success
