#! /bin/sh

# ls -A . | while read file; do
#     if [ -f $file ]; then
#         echo "$file is file"
#     fi
# done
# date_pattern=$(date '+%Y-%m-%d %H:%M:%S')
date_format=$(eval "date '+%Y-%m-%d'")
console_info=$(eval "who i am")
printf "Date: %s\nCurrent working directory: %s\nInfo: %s\n%s\n" \
"${date_format}" "$PWD" "${console_info}" "==================================" >&2
