CFLAGS = -g -Wall -std=c99 -pedantic -o

ascii: 
	gcc $(CFLAGS) ascii ascii.c

mx3lw:
	gcc $(CFLAGS) mx3lw mx3lw.c

mycat: 
	gcc $(CFLAGS) mycat mycat.c

numq: 
	gcc $(CFLAGS)  numq numq.c

myexpr:
	gcc $(CFLAGS) myexpr myexpr.c -lm

sort-by-length:
	gcc $(CFLAGS) sort-by-length sort-by-length.c

mycp: 
	gcc $(CFLAGS) mycp mycp.c

clean:
	rm -f *.o mycp mx3lw mycat numq ascii myexpr sort-by-length



