#! /bin/sh
# ###############################################
#          @author: Pavlo Rozbytskyi            #
#          @date: 23/04/2019                    #    
# ###############################################
file="$1"

longest_line=
current_line=

longest_length=0
current_length=0

# calculating length of the line $1
# prints out the length of the line in bible
calculate_line_length () {
    line=${1#* }
    len=${#line}
    # calculate line length
    printf "%d\n" "${#line}"
}

# processing line $1 
process_line () {
    current_line="$1"
    current_length=$(calculate_line_length "$1")

    if [ ${current_length} -gt ${longest_length} ]; then
        longest_length=${current_length}
        longest_line=${current_line}
    fi
}

if [ ! -f "${file}" ]; then
    printf "%s\n" "Error: file not found!" >&2
    exit 1
fi
{
    IFS= read current_line
    process_line "${current_line}"

    while IFS= read current_line; do
        process_line "${current_line}"
    done

    printf "%s\n" "${longest_line}"
} < "${file}"

exit 0