#! /bin/sh 

# $1 - error message
print_error () {
    printf "error: %s\n" "$1" >&2
}
# processing directory 
# $1 - directory name
process_directory () {
    echo "processing directory $1"
}

if [ "$#" -eq 0 ]; then
    # processing current directory
    process_directory "."
else
    while [ "$#" -gt 0 ]; do
        dir_name="$1"

        # checking is actually directory
        if [ -d "${dir_name}" ]; then 
            process_directory "${dir_name}"
        else
            print_error "\"${dir_name}\" isn't directory!"
            print_error "terminating"
            exit 1
        fi  

        shift 1
    done
fi


