#! /bin/sh 

# $1 - error message
print_error () {
    printf "error: %s\n" "$1" >&2
}
# processing directory 
# $1 - directory name
process_directory () {
    ls -lA "$1" | awk '
        BEGIN {
            ORS="\n"
            OFS="\t"
            print "tp\tno\tsz" 
        }
        { 
            # skipping first total line 
            if ($1!="total") {
                # getting type of the file
                type=substr($1, 0, 1);

                # device special files always have size zero
                if(type!="c" || type!="b"){
                    hash_map_size[type]+=$5
                }else{
                    hash_map_size[type]=0
                }
                hash_map_count[type]+=1
            }
        }
        END{ 
            for(key in hash_map_count){
                print key, hash_map_count[key], hash_map_size[key]
            }   
            print "---------------------"
            no_sum=0
            sz_sum=0

            for(key in hash_map_size){
                no_sum+=hash_map_count[key]
                sz_sum+=hash_map_size[key]
            }
            print "sum", no_sum, sz_sum
        }
        '
}

if [ "$#" -eq 0 ]; then
    # processing current directory
    process_directory "."
else
    while [ "$#" -gt 0 ]; do
        dir_name="$1"

        # checking is actually directory
        if [ -d "${dir_name}" ]; then 
            process_directory "${dir_name}"
        else
            print_error "\"${dir_name}\" isn't directory!"
            print_error "terminating"
            exit 1
        fi  

        shift 1
    done
fi


